### ISSUE TITLE
Changing volume waits for sound to finish, effectively lagging system

### ISSUE THREAD

**Issue by Acrivec** [irzyxa/Volume2#97]
**Describe the bug**
When you select a sound to be played when changing sound, and then you change the volume (scrolling over taskbar), the volume is changed a step by step, after each full play of the selected sound.

In previous versions it was possible to just scroll and the volume was set immediately -> the sound was overlapping on itself (correct way).

**Screenshots**
---

**Desktop (please complete the following information):**
 - Windows version: [e.g. 10(2004)]
 - Volume² version: [e.g. 1.1.5.404]

**Additional context**
If you scroll more (for example, to quickly make volume low, because of sound explosion), PC becomes laggy - mouse is moving very slowly, all until the volume finishes adjusting.

**Comment by irzyxa** [comment]
Did you try to use the latest version? 1.1.6.423
https://irzyxa.blogspot.com/p/downloads.html

**Comment by Acrivec** [comment]
Yes, same behaviour.

**Comment by irzyxa** [comment]
Cannot reproduce, can you send your sound file?

**Comment by Acrivec** [comment]
It's the built-in sound.

See video.

[2020-06-25_21-13-46.zip](https://github.com/irzyxa/Volume2/files/4833373/2020-06-25_21-13-46.zip)

**Comment by irzyxa** [comment]
Thanks, and now please screenshots with settings or Config.ini.
[https://github.com/irzyxa/Volume2/wiki/FAQ#4-where-is-configini-located](url)

**Comment by Acrivec** [comment]
[Config.zip](https://github.com/irzyxa/Volume2/files/4833534/Config.zip)

**Comment by irzyxa** [comment]
Probably you use Logitech mouse with enabled smooth scrolling.
https://github.com/irzyxa/Volume2/wiki/FAQ#7-incompatibility

**Comment by Acrivec** [comment]
Oh, interesting! I'm actually using Logitech mouse, but there is no 'smooth scrolling' setting at all.
I've tried installing Logitech Options but it does not detect any 'unified devices'. My mouse is g502 hero.

Also, my scroll in W10 apps is working quite OK. There is like a 0.05s delay on them (on firefox it's instant), but not so hard as on youtube videos I've seen.

**Comment by Acrivec** [comment]
As for lastest update which listed that Logitech SetPoint was fixed - continuing my last statement as I don't see any of 'smooth scroll' options, the issue persists. 

https://user-images.githubusercontent.com/26365504/103466519-38260f80-4d46-11eb-9fd7-28a9edf06cee.mp4


Note, that after 6th second I've stopped 'scrolling' and didn't scroll till the end of video.
There's also some system beeping, possibly related.

**Comment by Acrivec** [comment]
Unfortunately due to this bug still being in the app and also the fact, that for some time now the volume keeps changing (but very slowly, like one step with 2-3 seconds 'cooldown') after alt-tabbing and just scrolling in my browser (I'm using scroll on taskbar to control sound) I'm forced to uninstall. Can't live with those annoying bugs forever, and it's 1.5 years since I've reported this bug.
Cheers!

**Comment by irzyxa** [comment]
Sorry that you have been waiting so long. There was problem on systems more than Win7. I fixed it in the latest beta version and you can download it by link below:
https://irzyxa.blogspot.com/p/downloads.html

**Comment by irzyxa** [comment]
Yes it works like you said: after volume changing we always restart timer that should play sound and it plays it after some configurable delay. This option was always there, but just did not work on Windows 8, 10. Could you try disable sound and try to reproduce it? I think the issue is not in sound.
![image](https://user-images.githubusercontent.com/5119360/170267499-1584736b-ae30-41cf-9b32-732c5f79d6d0.png)

**Comment by Acrivec** [comment]
https://user-images.githubusercontent.com/26365504/170272819-a18189c0-8920-47ac-b10f-c5949d0e07d3.mp4

**Comment by Acrivec** [comment]
I've installed again and this bug is still present. I have no idea why did you close this bug report and never reopened it. It's not related to Logitech mouse as this occurs while using sound change knob on my keyboard, and it's happening only when Volume2 is opened. All provided with proofs of videos above.
